/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminDashboardRouteImport } from './routes/admin-dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as InstallRouteImport } from './routes/install'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PoRouteImport } from './routes/po'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as StudentDashboardRouteImport } from './routes/student-dashboard'
import { Route as StudentRegisterRouteImport } from './routes/student-register'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as AdminSplatRouteImport } from './routes/admin.$'
import { Route as ApiNssCloudRouteImport } from './routes/api/nss-cloud'
import { Route as PoIndexRouteImport } from './routes/po/index'
import { Route as PoAiRouteImport } from './routes/po/ai'
import { Route as PoAlumniRouteImport } from './routes/po/alumni'
import { Route as PoAttendanceRouteImport } from './routes/po/attendance'
import { Route as PoBackupRouteImport } from './routes/po/backup'
import { Route as PoBirthdaysRouteImport } from './routes/po/birthdays'
import { Route as PoCertificatesRouteImport } from './routes/po/certificates'
import { Route as PoEventsRouteImport } from './routes/po/events'
import { Route as PoGalleryRouteImport } from './routes/po/gallery'
import { Route as PoImpactRouteImport } from './routes/po/impact'
import { Route as PoLogsRouteImport } from './routes/po/logs'
import { Route as PoNoticesRouteImport } from './routes/po/notices'
import { Route as PoPressRouteImport } from './routes/po/press'
import { Route as PoReportsRouteImport } from './routes/po/reports'
import { Route as PoSettingsRouteImport } from './routes/po/settings'
import { Route as PoVolunteersRouteImport } from './routes/po/volunteers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PoRoute = PoRouteImport.update({
  id: '/po',
  path: '/po',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student-dashboard',
  path: '/student-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRegisterRoute = StudentRegisterRouteImport.update({
  id: '/student-register',
  path: '/student-register',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AdminRoute,
} as any)
const ApiNssCloudRoute = ApiNssCloudRouteImport.update({
  id: '/api/nss-cloud',
  path: '/api/nss-cloud',
  getParentRoute: () => rootRouteImport,
} as any)
const PoIndexRoute = PoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PoRoute,
} as any)
const PoAiRoute = PoAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => PoRoute,
} as any)
const PoAlumniRoute = PoAlumniRouteImport.update({
  id: '/alumni',
  path: '/alumni',
  getParentRoute: () => PoRoute,
} as any)
const PoAttendanceRoute = PoAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => PoRoute,
} as any)
const PoBackupRoute = PoBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => PoRoute,
} as any)
const PoBirthdaysRoute = PoBirthdaysRouteImport.update({
  id: '/birthdays',
  path: '/birthdays',
  getParentRoute: () => PoRoute,
} as any)
const PoCertificatesRoute = PoCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => PoRoute,
} as any)
const PoEventsRoute = PoEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => PoRoute,
} as any)
const PoGalleryRoute = PoGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => PoRoute,
} as any)
const PoImpactRoute = PoImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => PoRoute,
} as any)
const PoLogsRoute = PoLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => PoRoute,
} as any)
const PoNoticesRoute = PoNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => PoRoute,
} as any)
const PoPressRoute = PoPressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => PoRoute,
} as any)
const PoReportsRoute = PoReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => PoRoute,
} as any)
const PoSettingsRoute = PoSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PoRoute,
} as any)
const PoVolunteersRoute = PoVolunteersRouteImport.update({
  id: '/volunteers',
  path: '/volunteers',
  getParentRoute: () => PoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-dashboard': typeof AdminDashboardRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/install': typeof InstallRoute
  '/login': typeof LoginRoute
  '/po': typeof PoRouteWithChildren
  '/register': typeof RegisterRoute
  '/student-dashboard': typeof StudentDashboardRoute
  '/student-register': typeof StudentRegisterRoute
  '/verify': typeof VerifyRoute
  '/volunteer': typeof VolunteerRoute
  '/admin/$': typeof AdminSplatRoute
  '/api/nss-cloud': typeof ApiNssCloudRoute
  '/po/ai': typeof PoAiRoute
  '/po/alumni': typeof PoAlumniRoute
  '/po/attendance': typeof PoAttendanceRoute
  '/po/backup': typeof PoBackupRoute
  '/po/birthdays': typeof PoBirthdaysRoute
  '/po/certificates': typeof PoCertificatesRoute
  '/po/events': typeof PoEventsRoute
  '/po/gallery': typeof PoGalleryRoute
  '/po/impact': typeof PoImpactRoute
  '/po/logs': typeof PoLogsRoute
  '/po/notices': typeof PoNoticesRoute
  '/po/press': typeof PoPressRoute
  '/po/reports': typeof PoReportsRoute
  '/po/settings': typeof PoSettingsRoute
  '/po/volunteers': typeof PoVolunteersRoute
  '/po/': typeof PoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-dashboard': typeof AdminDashboardRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/install': typeof InstallRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/student-dashboard': typeof StudentDashboardRoute
  '/student-register': typeof StudentRegisterRoute
  '/verify': typeof VerifyRoute
  '/volunteer': typeof VolunteerRoute
  '/admin/$': typeof AdminSplatRoute
  '/api/nss-cloud': typeof ApiNssCloudRoute
  '/po/ai': typeof PoAiRoute
  '/po/alumni': typeof PoAlumniRoute
  '/po/attendance': typeof PoAttendanceRoute
  '/po/backup': typeof PoBackupRoute
  '/po/birthdays': typeof PoBirthdaysRoute
  '/po/certificates': typeof PoCertificatesRoute
  '/po/events': typeof PoEventsRoute
  '/po/gallery': typeof PoGalleryRoute
  '/po/impact': typeof PoImpactRoute
  '/po/logs': typeof PoLogsRoute
  '/po/notices': typeof PoNoticesRoute
  '/po/press': typeof PoPressRoute
  '/po/reports': typeof PoReportsRoute
  '/po/settings': typeof PoSettingsRoute
  '/po/volunteers': typeof PoVolunteersRoute
  '/po': typeof PoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-dashboard': typeof AdminDashboardRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/install': typeof InstallRoute
  '/login': typeof LoginRoute
  '/po': typeof PoRouteWithChildren
  '/register': typeof RegisterRoute
  '/student-dashboard': typeof StudentDashboardRoute
  '/student-register': typeof StudentRegisterRoute
  '/verify': typeof VerifyRoute
  '/volunteer': typeof VolunteerRoute
  '/admin/$': typeof AdminSplatRoute
  '/api/nss-cloud': typeof ApiNssCloudRoute
  '/po/ai': typeof PoAiRoute
  '/po/alumni': typeof PoAlumniRoute
  '/po/attendance': typeof PoAttendanceRoute
  '/po/backup': typeof PoBackupRoute
  '/po/birthdays': typeof PoBirthdaysRoute
  '/po/certificates': typeof PoCertificatesRoute
  '/po/events': typeof PoEventsRoute
  '/po/gallery': typeof PoGalleryRoute
  '/po/impact': typeof PoImpactRoute
  '/po/logs': typeof PoLogsRoute
  '/po/notices': typeof PoNoticesRoute
  '/po/press': typeof PoPressRoute
  '/po/reports': typeof PoReportsRoute
  '/po/settings': typeof PoSettingsRoute
  '/po/volunteers': typeof PoVolunteersRoute
  '/po/': typeof PoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-dashboard'
    | '/contact'
    | '/gallery'
    | '/install'
    | '/login'
    | '/po'
    | '/register'
    | '/student-dashboard'
    | '/student-register'
    | '/verify'
    | '/volunteer'
    | '/admin/$'
    | '/api/nss-cloud'
    | '/po/ai'
    | '/po/alumni'
    | '/po/attendance'
    | '/po/backup'
    | '/po/birthdays'
    | '/po/certificates'
    | '/po/events'
    | '/po/gallery'
    | '/po/impact'
    | '/po/logs'
    | '/po/notices'
    | '/po/press'
    | '/po/reports'
    | '/po/settings'
    | '/po/volunteers'
    | '/po/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-dashboard'
    | '/contact'
    | '/gallery'
    | '/install'
    | '/login'
    | '/register'
    | '/student-dashboard'
    | '/student-register'
    | '/verify'
    | '/volunteer'
    | '/admin/$'
    | '/api/nss-cloud'
    | '/po/ai'
    | '/po/alumni'
    | '/po/attendance'
    | '/po/backup'
    | '/po/birthdays'
    | '/po/certificates'
    | '/po/events'
    | '/po/gallery'
    | '/po/impact'
    | '/po/logs'
    | '/po/notices'
    | '/po/press'
    | '/po/reports'
    | '/po/settings'
    | '/po/volunteers'
    | '/po'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-dashboard'
    | '/contact'
    | '/gallery'
    | '/install'
    | '/login'
    | '/po'
    | '/register'
    | '/student-dashboard'
    | '/student-register'
    | '/verify'
    | '/volunteer'
    | '/admin/$'
    | '/api/nss-cloud'
    | '/po/ai'
    | '/po/alumni'
    | '/po/attendance'
    | '/po/backup'
    | '/po/birthdays'
    | '/po/certificates'
    | '/po/events'
    | '/po/gallery'
    | '/po/impact'
    | '/po/logs'
    | '/po/notices'
    | '/po/press'
    | '/po/reports'
    | '/po/settings'
    | '/po/volunteers'
    | '/po/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminDashboardRoute: typeof AdminDashboardRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  InstallRoute: typeof InstallRoute
  LoginRoute: typeof LoginRoute
  PoRoute: typeof PoRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentRegisterRoute: typeof StudentRegisterRoute
  VerifyRoute: typeof VerifyRoute
  VolunteerRoute: typeof VolunteerRoute
  ApiNssCloudRoute: typeof ApiNssCloudRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard': {
      id: '/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/po': {
      id: '/po'
      path: '/po'
      fullPath: '/po'
      preLoaderRoute: typeof PoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-dashboard': {
      id: '/student-dashboard'
      path: '/student-dashboard'
      fullPath: '/student-dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-register': {
      id: '/student-register'
      path: '/student-register'
      fullPath: '/student-register'
      preLoaderRoute: typeof StudentRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/nss-cloud': {
      id: '/api/nss-cloud'
      path: '/api/nss-cloud'
      fullPath: '/api/nss-cloud'
      preLoaderRoute: typeof ApiNssCloudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/po/': {
      id: '/po/'
      path: '/'
      fullPath: '/po/'
      preLoaderRoute: typeof PoIndexRouteImport
      parentRoute: typeof PoRoute
    }
    '/po/ai': {
      id: '/po/ai'
      path: '/ai'
      fullPath: '/po/ai'
      preLoaderRoute: typeof PoAiRouteImport
      parentRoute: typeof PoRoute
    }
    '/po/alumni': {
      id: '/po/alumni'
      path: '/alumni'
      fullPath: '/po/alumni'
      preLoaderRoute: typeof PoAlumniRouteImport
      parentRoute: typeof PoRoute
    }
    '/po/attendance': {
      id: '/po/attendance'
      path: '/attendance'
      fullPath: '/po/attendance'
      preLoaderRoute: typeof PoAttendanceRouteImport
      parentRoute: typeof PoRoute
    }
    '/po/backup': {
      id: '/po/backup'
      path: '/backup'
      fullPath: '/po/backup'
      preLoaderRoute: typeof PoBackupRouteImport
      parentRoute: typeof PoRoute
    }
    '/po/birthdays': {
      id: '/po/birthdays'
      path: '/birthdays'
      fullPath: '/po/birthdays'
      preLoaderRoute: typeof PoBirthdaysRouteImport
      parentRoute: typeof PoRoute
    }
    '/po/certificates': {
      id: '/po/certificates'
      path: '/certificates'
      fullPath: '/po/certificates'
      preLoaderRoute: typeof PoCertificatesRouteImport
      parentRoute: typeof PoRoute
    }
    '/po/events': {
      id: '/po/events'
      path: '/events'
      fullPath: '/po/events'
      preLoaderRoute: typeof PoEventsRouteImport
      parentRoute: typeof PoRoute
    }
    '/po/gallery': {
      id: '/po/gallery'
      path: '/gallery'
      fullPath: '/po/gallery'
      preLoaderRoute: typeof PoGalleryRouteImport
      parentRoute: typeof PoRoute
    }
    '/po/impact': {
      id: '/po/impact'
      path: '/impact'
      fullPath: '/po/impact'
      preLoaderRoute: typeof PoImpactRouteImport
      parentRoute: typeof PoRoute
    }
    '/po/logs': {
      id: '/po/logs'
      path: '/logs'
      fullPath: '/po/logs'
      preLoaderRoute: typeof PoLogsRouteImport
      parentRoute: typeof PoRoute
    }
    '/po/notices': {
      id: '/po/notices'
      path: '/notices'
      fullPath: '/po/notices'
      preLoaderRoute: typeof PoNoticesRouteImport
      parentRoute: typeof PoRoute
    }
    '/po/press': {
      id: '/po/press'
      path: '/press'
      fullPath: '/po/press'
      preLoaderRoute: typeof PoPressRouteImport
      parentRoute: typeof PoRoute
    }
    '/po/reports': {
      id: '/po/reports'
      path: '/reports'
      fullPath: '/po/reports'
      preLoaderRoute: typeof PoReportsRouteImport
      parentRoute: typeof PoRoute
    }
    '/po/settings': {
      id: '/po/settings'
      path: '/settings'
      fullPath: '/po/settings'
      preLoaderRoute: typeof PoSettingsRouteImport
      parentRoute: typeof PoRoute
    }
    '/po/volunteers': {
      id: '/po/volunteers'
      path: '/volunteers'
      fullPath: '/po/volunteers'
      preLoaderRoute: typeof PoVolunteersRouteImport
      parentRoute: typeof PoRoute
    }
  }
}

interface AdminRouteChildren {
  AdminSplatRoute: typeof AdminSplatRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSplatRoute: AdminSplatRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PoRouteChildren {
  PoAiRoute: typeof PoAiRoute
  PoAlumniRoute: typeof PoAlumniRoute
  PoAttendanceRoute: typeof PoAttendanceRoute
  PoBackupRoute: typeof PoBackupRoute
  PoBirthdaysRoute: typeof PoBirthdaysRoute
  PoCertificatesRoute: typeof PoCertificatesRoute
  PoEventsRoute: typeof PoEventsRoute
  PoGalleryRoute: typeof PoGalleryRoute
  PoImpactRoute: typeof PoImpactRoute
  PoLogsRoute: typeof PoLogsRoute
  PoNoticesRoute: typeof PoNoticesRoute
  PoPressRoute: typeof PoPressRoute
  PoReportsRoute: typeof PoReportsRoute
  PoSettingsRoute: typeof PoSettingsRoute
  PoVolunteersRoute: typeof PoVolunteersRoute
  PoIndexRoute: typeof PoIndexRoute
}

const PoRouteChildren: PoRouteChildren = {
  PoAiRoute: PoAiRoute,
  PoAlumniRoute: PoAlumniRoute,
  PoAttendanceRoute: PoAttendanceRoute,
  PoBackupRoute: PoBackupRoute,
  PoBirthdaysRoute: PoBirthdaysRoute,
  PoCertificatesRoute: PoCertificatesRoute,
  PoEventsRoute: PoEventsRoute,
  PoGalleryRoute: PoGalleryRoute,
  PoImpactRoute: PoImpactRoute,
  PoLogsRoute: PoLogsRoute,
  PoNoticesRoute: PoNoticesRoute,
  PoPressRoute: PoPressRoute,
  PoReportsRoute: PoReportsRoute,
  PoSettingsRoute: PoSettingsRoute,
  PoVolunteersRoute: PoVolunteersRoute,
  PoIndexRoute: PoIndexRoute,
}

const PoRouteWithChildren = PoRoute._addFileChildren(PoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminDashboardRoute: AdminDashboardRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  InstallRoute: InstallRoute,
  LoginRoute: LoginRoute,
  PoRoute: PoRouteWithChildren,
  RegisterRoute: RegisterRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentRegisterRoute: StudentRegisterRoute,
  VerifyRoute: VerifyRoute,
  VolunteerRoute: VolunteerRoute,
  ApiNssCloudRoute: ApiNssCloudRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
